### ISSUE TITLE
Tickbox for refused expenses

### ISSUE THREAD

**Issue by skylark1848** [bmispelon/adatozz#7]
Create tickbox in front of expense rows to mark invoices that were not accepted ("Elutasítva") by the authority.

**Comment by bmispelon** [comment]
I added a pull request for it there: https://github.com/bmispelon/adatozz/pull/8

Can you help me with the translation of the .po file?

**Comment by bmispelon** [comment]
I also realized that I could make the form page full-width in order to gain a tiny bit of vertical space.

What do you think?

![adatozz-option-current](https://cloud.githubusercontent.com/assets/6345/9035561/662e6d18-39d9-11e5-9450-6c8386cbd660.png)
![adatozz-option-fluid](https://cloud.githubusercontent.com/assets/6345/9035562/662fbc04-39d9-11e5-973a-5bce830c3144.png)

**Comment by skylark1848** [comment]
I like it, I think it really matters to have that space.
